### PR TITLE
Add Python section and 5 answers.

### PR DESCRIPTION
**Pull request by mazulo**
Add answers for:
- "Why are banks like JP Morgan and Bank of America Merrill Lynch using Python to replace historic legacy systems built in Java/C++?"
- "What are killer Python tips which could make our coder lives more productive, easier and happier?
- "10 Myths of Enterprise Python"
- "What are some of the best time-saving tips for Python?"
- "Why is Python a language of choice for data scientists?"

### CODE REVIEW

**Comment by simonweil** [comment]
:+1:

**Comment by mazulo** [comment]
:smile:

**Comment by cyberglot** [comment]
@mazulo thanks :smile:

**Comment by RomuloOliveira** [comment]
Hi, sorry to comment in a closed PR (I just saw it now and I'm not an official maintainer), but it would be nice to add Python to "TOC". Also, I think that's better if you provide a link to the answer, and not only to the question (I've already did it myself :stuck_out_tongue:).

**Comment by cyberglot** [comment]
I am going to do it later on. No worries.

**Comment by RomuloOliveira** [comment]
Ah, ok, thanks! (and sorry if my comment was inappropriate)

**Comment by cyberglot** [comment]
No problem. You're free to comment anytime you want. :smile: I have seen it, but I am too lazy to do it right now.

**Comment by mazulo** [comment]
@jugoncalves I can do it :grin:

**Pull request merged**
